spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # 关闭缓存，生产环境建议开启
    prefix: classpath:/templates/  # 默认前缀
    suffix: .html  # 默认后缀

logging:
  level:
    com.ljx.gulimall: error