server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # 关闭缓存，生产环境建议开启
    prefix: classpath:/templates/  # 默认前缀
    suffix: .html  # 默认后缀
  application:
    name: gulimall-test-sso-client
  redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    timeout: 1800000
  session:
    store-type: redis

logging:
  level:
    com.ljx.gulimall: error